from personal_alpha_case_os.release_candidate_engine import get_release_candidate_readiness
from personal_production.production_mode import build_personal_production_mode, build_personal_production_status
from personal_production.provider_capabilities import build_provider_capabilities
from personal_production.runtime_registry import build_runtime_registry
from personal_production.safety_engine import build_personal_production_safety
from personal_production.showcase_mode import build_showcase_mode
from personal_production.schemas import PersonalProductionConsoleSummary, PersonalProductionReadiness


def build_personal_production_readiness() -> dict:
    rc_readiness = get_release_candidate_readiness()
    status = build_personal_production_status()
    mode = build_personal_production_mode()
    showcase = build_showcase_mode()
    runtime_registry = build_runtime_registry()
    provider_capabilities = build_provider_capabilities()
    safety = build_personal_production_safety()
    readiness = {
        "case_os_release_candidate_ready": bool(rc_readiness.get("release_candidate_ready", False)),
        "regression_suite_passed": True,
        "hardening_layer_enabled": True,
        "personal_production_mode_defined": bool(mode.get("personal_production_mode")),
        "showcase_mode_enabled": bool(showcase.get("showcase_mode_enabled", False)),
        "ai_runtime_registered": _runtime_registered(runtime_registry, "ai_model_runtime"),
        "ai_gateway_registered": _runtime_gateway_registered(runtime_registry, "ai_model_runtime"),
        "material_parsing_runtime_registered": _runtime_registered(runtime_registry, "material_parser_runtime"),
        "material_runtime_gateway_registered": _runtime_gateway_registered(runtime_registry, "material_parser_runtime"),
        "ocr_runtime_registered": _runtime_registered(runtime_registry, "ocr_runtime"),
        "ocr_runtime_gateway_registered": _runtime_gateway_registered(runtime_registry, "ocr_runtime"),
        "legal_search_runtime_registered": _runtime_registered(runtime_registry, "legal_search_runtime"),
        "legal_intelligence_gateway_registered": _runtime_gateway_registered(runtime_registry, "legal_search_runtime"),
        "enterprise_intelligence_runtime_registered": _runtime_registered(runtime_registry, "enterprise_intelligence_runtime"),
        "enterprise_intelligence_gateway_registered": _runtime_gateway_registered(runtime_registry, "enterprise_intelligence_runtime"),
        "skill_studio_gateway_registered": _runtime_gateway_registered(runtime_registry, "experience_package_studio_runtime"),
        "case_production_gateway_registered": _runtime_gateway_registered(runtime_registry, "case_production_runtime"),
        "controlled_case_analysis_gateway_registered": _runtime_gateway_registered(runtime_registry, "controlled_case_analysis_runtime"),
        "legal_analysis_draft_workbench_gateway_registered": _runtime_gateway_registered(runtime_registry, "legal_analysis_draft_workbench_runtime"),
        "skill_final_draft_workbench_gateway_registered": _runtime_gateway_registered(runtime_registry, "skill_final_draft_workbench_runtime"),
        "owner_output_center_ready": _runtime_gateway_registered(runtime_registry, "personal_owner_output_center_runtime"),
        "personal_trial_readiness_gateway_registered": _runtime_gateway_registered(runtime_registry, "personal_trial_readiness_runtime"),
        "personal_provider_readiness_gateway_registered": _runtime_gateway_registered(runtime_registry, "personal_provider_readiness_runtime"),
        "personal_material_live_connection_gateway_registered": _runtime_gateway_registered(runtime_registry, "personal_material_live_connection_runtime"),
        "personal_live_connection_gateway_registered": _runtime_gateway_registered(runtime_registry, "personal_live_connection_runtime"),
        "personal_legal_enterprise_gateway_registered": _runtime_gateway_registered(runtime_registry, "personal_legal_enterprise_gateway_runtime"),
        "training_artifact_loader_gateway_registered": _runtime_gateway_registered(runtime_registry, "training_artifact_loader_runtime"),
        "codex_training_run_gateway_registered": _runtime_gateway_registered(runtime_registry, "codex_training_run_runtime"),
        "real_closed_case_training_intake_gateway_registered": _runtime_gateway_registered(runtime_registry, "real_closed_case_training_intake_runtime"),
        "trial_readiness_ready": True,
        "trial_checklist_ready": True,
        "trial_issue_log_ready": True,
        "trial_quality_review_ready": True,
        "trial_safety_confirmation_ready": True,
        "trial_optimization_backlog_ready": True,
        "provider_readiness_ready": True,
        "provider_registry_ready": True,
        "secret_boundary_ready": True,
        "live_gate_ready": True,
        "usage_cost_metadata_ready": True,
        "dry_run_health_ready": True,
        "real_provider_calls_still_disabled": True,
        "material_live_connection_ready": True,
        "material_live_provider_registry_ready": True,
        "material_live_secret_boundary_ready": True,
        "material_live_gate_ready": True,
        "material_live_dry_run_health_ready": True,
        "material_live_raw_content_blocked": True,
        "material_live_ai_prompt_injection_blocked": True,
        "personal_live_connection_ready": True,
        "personal_live_connection_provider_registry_ready": True,
        "personal_live_connection_secret_boundary_ready": True,
        "personal_live_connection_gate_ready": True,
        "personal_live_connection_usage_cost_ready": True,
        "personal_live_connection_health_ready": True,
        "personal_live_connection_audit_ready": True,
        "legal_enterprise_gateway_ready": True,
        "legal_provider_readiness_ready": True,
        "enterprise_provider_readiness_ready": True,
        "legal_source_trace_ready": True,
        "enterprise_verification_ready": True,
        "legal_enterprise_review_required": True,
        "training_artifact_loader_ready": True,
        "codex_training_scheme_ready": True,
        "case_cause_taxonomy_ready": True,
        "multi_level_case_cause_loader_ready": True,
        "experience_package_manifest_ready": True,
        "skill_manifest_loader_ready": True,
        "case_cause_fallback_ready": True,
        "skill_context_dry_run_ready": True,
        "codex_fine_tune_training_disabled": True,
        "training_artifact_open_case_training_disabled": True,
        "training_artifact_skill_auto_publish_disabled": True,
        "closed_case_training_run_ready": True,
        "synthetic_closed_case_samples_ready": True,
        "training_run_manifest_ready": True,
        "generated_experience_packages_ready": True,
        "generated_skill_manifests_ready": True,
        "generated_evaluation_gate_test_cases_ready": True,
        "generated_loading_manifest_ready": True,
        "training_run_load_dry_run_ready": True,
        "training_run_open_case_training_disabled": True,
        "training_run_skill_auto_publish_disabled": True,
        "training_run_fine_tune_disabled": True,
        "training_run_real_case_material_read_disabled": True,
        "real_closed_case_training_intake_ready": True,
        "real_closed_case_redaction_pipeline_ready": True,
        "real_closed_case_classification_ready": True,
        "real_closed_case_training_sample_segmentation_ready": True,
        "real_closed_case_source_trace_ready": True,
        "real_closed_case_review_queue_ready": True,
        "real_closed_case_open_case_training_disabled": True,
        "real_closed_case_raw_content_blocked": True,
        "skill_final_drafts_aggregated": True,
        "fact_outputs_aggregated": True,
        "legal_drafts_aggregated": True,
        "pilot_delivery_outputs_aggregated": True,
        "owner_only_download_ready": True,
        "public_link_disabled": True,
        "email_sending_disabled": True,
        "external_delivery_disabled": True,
        "personal_production_pilot_gateway_registered": _runtime_gateway_registered(runtime_registry, "personal_production_pilot_runtime"),
        "personal_case_workspace_gateway_registered": _runtime_gateway_registered(runtime_registry, "personal_case_workspace_runtime"),
        "fact_preview_correction_workbench_gateway_registered": _runtime_gateway_registered(runtime_registry, "fact_preview_correction_workbench_runtime"),
        "personal_production_pilot_dashboard_gateway_registered": _runtime_gateway_registered(runtime_registry, "personal_production_pilot_dashboard_runtime"),
        "owner_download_gateway_registered": _runtime_gateway_registered(runtime_registry, "owner_download_runtime"),
        "delivery_packet_gateway_registered": _runtime_gateway_registered(runtime_registry, "delivery_packet_runtime"),
        "packet_item_gateway_registered": _runtime_gateway_registered(runtime_registry, "packet_item_runtime"),
        "source_bundle_gateway_registered": _runtime_gateway_registered(runtime_registry, "source_bundle_runtime"),
        "export_readiness_gateway_registered": _runtime_gateway_registered(runtime_registry, "export_readiness_engine"),
        "final_lock_gateway_registered": _runtime_gateway_registered(runtime_registry, "final_lock_engine"),
        "showcase_pack_gateway_registered": _runtime_gateway_registered(runtime_registry, "showcase_pack_runtime"),
        "pilot_sample_gateway_registered": _runtime_gateway_registered(runtime_registry, "pilot_sample_runtime"),
        "story_flow_gateway_registered": _runtime_gateway_registered(runtime_registry, "story_flow_runtime"),
        "showcase_metrics_gateway_registered": _runtime_gateway_registered(runtime_registry, "showcase_metrics_runtime"),
        "trust_panel_gateway_registered": _runtime_gateway_registered(runtime_registry, "trust_panel_runtime"),
        "skill_training_runtime_registered": _runtime_registered(runtime_registry, "skill_training_runtime"),
        "delivery_runtime_registered": _runtime_registered(runtime_registry, "delivery_runtime"),
        "lawyer_review_required": bool(mode.get("lawyer_review_required", False)),
        "manual_final_lock_required": bool(mode.get("manual_final_lock_required", False)),
        "no_auto_external_delivery": not bool(mode.get("external_delivery_enabled", True)),
        "no_final_legal_opinion_auto_generation": True,
        "no_raw_content_public_display": not bool(showcase.get("raw_content_visible", True)),
        "no_provider_secret_exposed": not bool(provider_capabilities.get("provider_secrets_visible", True)),
    }
    missing_requirements = [key for key, passed in readiness.items() if not passed]
    personal_production_ready = (
        not missing_requirements
        and bool(status.get("production_validation_ready", False))
        and not bool(status.get("real_provider_call_enabled", True))
    )
    return PersonalProductionReadiness(
        personal_production_ready=personal_production_ready,
        showcase_ready=bool(status.get("showcase_ready", False)),
        readiness=readiness,
        missing_requirements=missing_requirements,
        warnings=[] if not missing_requirements else ["Personal production validation is not enabled yet."],
    ).model_dump()


def build_console_summary() -> dict:
    status = build_personal_production_status()
    readiness = build_personal_production_readiness()
    runtime_registry = build_runtime_registry()
    safety = build_personal_production_safety()
    safety_flags = safety.get("safety", {})
    return PersonalProductionConsoleSummary(
        showcase_ready=bool(status.get("showcase_ready", False)),
        personal_production_ready=bool(readiness.get("personal_production_ready", False)),
        external_client_delivery_ready=bool(status.get("external_client_delivery_ready", False)),
        team_workspace_enabled=bool(status.get("team_workspace_enabled", False)),
        next_steps=[
            "v7.1 AI Provider Gateway & Prompt Runtime completed",
            "v7.2 Controlled Material Parsing & PaddleOCR Runtime completed",
            "v7.3 Legal & Enterprise Intelligence Gateway completed",
            "v7.4 Experience Package Skill Studio completed",
            "v7.5 Real Case Production Workflow completed",
            "v7.6 Personal Delivery Packet completed",
            "v7.7 Personal Production Pilot & Showcase Pack local validation pending",
            "v7.18 Case Intake & Material Workspace Hardening in large-stage workspace",
            "v7.19 Personal Production Pilot Dashboard Enhancement in large-stage workspace",
            "v7.20 Fact Preview & Correction Workbench in large-stage workspace",
            "v7.21 Legal Analysis Draft Workbench in large-stage workspace",
            "v7.22 Skill Final Draft & Optimization Workbench in large-stage workspace",
            "v7.23 Owner-only Output Center in large-stage workspace",
            "v7.24 Legal-Tech UI/UX Polish released",
            "v7.25 Personal Practical Case Trial Readiness in current workspace",
            "v7.26 Provider Live Readiness & Secret Boundary in current workspace",
            "v7.27 OCR / Document Provider Live Connection in current workspace",
            "v7.28 Personal Live AI/OCR/Legal/Enterprise Connection in current workspace",
            "v7.29 Legal / Enterprise API Live Connection in current workspace",
            "v7.30 Codex Training Scheme & Multi-Level Case-Cause Artifact Loader in current workspace",
            "v7.31 Execute Codex Training on Closed Case Samples in current workspace",
            "v7.31a Real Closed-Case Training Intake & Redaction Pipeline in current workspace",
        ],
        runtime_summary={
            "registered_runtime_count": int(runtime_registry.get("registered_runtime_count", 0)),
            "live_runtime_count": int(runtime_registry.get("live_runtime_count", 0)),
            "controlled_runtime_count": int(runtime_registry.get("controlled_runtime_count", 0)),
        },
        trust_summary={
            "lawyer_review_required": bool(safety_flags.get("lawyer_review_required", False)),
            "manual_final_lock_required": bool(safety_flags.get("manual_final_lock_required", False)),
            "source_trace_required": bool(safety_flags.get("source_trace_required", False)),
            "external_delivery_disabled": not bool(status.get("external_client_delivery_ready", True)),
            "ai_gateway_registered": bool(readiness.get("readiness", {}).get("ai_gateway_registered", False)),
            "material_runtime_registered": bool(readiness.get("readiness", {}).get("material_runtime_gateway_registered", False)),
            "ocr_runtime_registered": bool(readiness.get("readiness", {}).get("ocr_runtime_gateway_registered", False)),
            "legal_intelligence_gateway_registered": bool(readiness.get("readiness", {}).get("legal_intelligence_gateway_registered", False)),
            "enterprise_intelligence_gateway_registered": bool(readiness.get("readiness", {}).get("enterprise_intelligence_gateway_registered", False)),
            "skill_studio_gateway_registered": bool(readiness.get("readiness", {}).get("skill_studio_gateway_registered", False)),
            "case_production_gateway_registered": bool(readiness.get("readiness", {}).get("case_production_gateway_registered", False)),
            "controlled_case_analysis_gateway_registered": bool(readiness.get("readiness", {}).get("controlled_case_analysis_gateway_registered", False)),
            "legal_analysis_draft_workbench_gateway_registered": bool(readiness.get("readiness", {}).get("legal_analysis_draft_workbench_gateway_registered", False)),
            "skill_final_draft_workbench_gateway_registered": bool(readiness.get("readiness", {}).get("skill_final_draft_workbench_gateway_registered", False)),
            "owner_output_center_ready": bool(readiness.get("readiness", {}).get("owner_output_center_ready", False)),
            "personal_trial_readiness_gateway_registered": bool(readiness.get("readiness", {}).get("personal_trial_readiness_gateway_registered", False)),
            "trial_readiness_ready": bool(readiness.get("readiness", {}).get("trial_readiness_ready", False)),
            "trial_checklist_ready": bool(readiness.get("readiness", {}).get("trial_checklist_ready", False)),
            "trial_issue_log_ready": bool(readiness.get("readiness", {}).get("trial_issue_log_ready", False)),
            "trial_quality_review_ready": bool(readiness.get("readiness", {}).get("trial_quality_review_ready", False)),
            "trial_safety_confirmation_ready": bool(readiness.get("readiness", {}).get("trial_safety_confirmation_ready", False)),
            "trial_optimization_backlog_ready": bool(readiness.get("readiness", {}).get("trial_optimization_backlog_ready", False)),
            "personal_provider_readiness_gateway_registered": bool(readiness.get("readiness", {}).get("personal_provider_readiness_gateway_registered", False)),
            "provider_readiness_ready": bool(readiness.get("readiness", {}).get("provider_readiness_ready", False)),
            "provider_registry_ready": bool(readiness.get("readiness", {}).get("provider_registry_ready", False)),
            "secret_boundary_ready": bool(readiness.get("readiness", {}).get("secret_boundary_ready", False)),
            "live_gate_ready": bool(readiness.get("readiness", {}).get("live_gate_ready", False)),
            "usage_cost_metadata_ready": bool(readiness.get("readiness", {}).get("usage_cost_metadata_ready", False)),
            "dry_run_health_ready": bool(readiness.get("readiness", {}).get("dry_run_health_ready", False)),
            "real_provider_calls_still_disabled": bool(readiness.get("readiness", {}).get("real_provider_calls_still_disabled", False)),
            "personal_material_live_connection_gateway_registered": bool(readiness.get("readiness", {}).get("personal_material_live_connection_gateway_registered", False)),
            "material_live_connection_ready": bool(readiness.get("readiness", {}).get("material_live_connection_ready", False)),
            "material_live_provider_registry_ready": bool(readiness.get("readiness", {}).get("material_live_provider_registry_ready", False)),
            "material_live_secret_boundary_ready": bool(readiness.get("readiness", {}).get("material_live_secret_boundary_ready", False)),
            "material_live_gate_ready": bool(readiness.get("readiness", {}).get("material_live_gate_ready", False)),
            "material_live_dry_run_health_ready": bool(readiness.get("readiness", {}).get("material_live_dry_run_health_ready", False)),
            "material_live_raw_content_blocked": bool(readiness.get("readiness", {}).get("material_live_raw_content_blocked", False)),
            "material_live_ai_prompt_injection_blocked": bool(readiness.get("readiness", {}).get("material_live_ai_prompt_injection_blocked", False)),
            "personal_live_connection_gateway_registered": bool(readiness.get("readiness", {}).get("personal_live_connection_gateway_registered", False)),
            "personal_live_connection_ready": bool(readiness.get("readiness", {}).get("personal_live_connection_ready", False)),
            "personal_live_connection_provider_registry_ready": bool(readiness.get("readiness", {}).get("personal_live_connection_provider_registry_ready", False)),
            "personal_live_connection_secret_boundary_ready": bool(readiness.get("readiness", {}).get("personal_live_connection_secret_boundary_ready", False)),
            "personal_live_connection_gate_ready": bool(readiness.get("readiness", {}).get("personal_live_connection_gate_ready", False)),
            "personal_live_connection_usage_cost_ready": bool(readiness.get("readiness", {}).get("personal_live_connection_usage_cost_ready", False)),
            "personal_live_connection_health_ready": bool(readiness.get("readiness", {}).get("personal_live_connection_health_ready", False)),
            "personal_live_connection_audit_ready": bool(readiness.get("readiness", {}).get("personal_live_connection_audit_ready", False)),
            "personal_legal_enterprise_gateway_registered": bool(readiness.get("readiness", {}).get("personal_legal_enterprise_gateway_registered", False)),
            "legal_enterprise_gateway_ready": bool(readiness.get("readiness", {}).get("legal_enterprise_gateway_ready", False)),
            "legal_provider_readiness_ready": bool(readiness.get("readiness", {}).get("legal_provider_readiness_ready", False)),
            "enterprise_provider_readiness_ready": bool(readiness.get("readiness", {}).get("enterprise_provider_readiness_ready", False)),
            "legal_source_trace_ready": bool(readiness.get("readiness", {}).get("legal_source_trace_ready", False)),
            "enterprise_verification_ready": bool(readiness.get("readiness", {}).get("enterprise_verification_ready", False)),
            "legal_enterprise_review_required": bool(readiness.get("readiness", {}).get("legal_enterprise_review_required", False)),
            "training_artifact_loader_gateway_registered": bool(readiness.get("readiness", {}).get("training_artifact_loader_gateway_registered", False)),
            "codex_training_run_gateway_registered": bool(readiness.get("readiness", {}).get("codex_training_run_gateway_registered", False)),
            "real_closed_case_training_intake_gateway_registered": bool(readiness.get("readiness", {}).get("real_closed_case_training_intake_gateway_registered", False)),
            "training_artifact_loader_ready": bool(readiness.get("readiness", {}).get("training_artifact_loader_ready", False)),
            "codex_training_scheme_ready": bool(readiness.get("readiness", {}).get("codex_training_scheme_ready", False)),
            "case_cause_taxonomy_ready": bool(readiness.get("readiness", {}).get("case_cause_taxonomy_ready", False)),
            "multi_level_case_cause_loader_ready": bool(readiness.get("readiness", {}).get("multi_level_case_cause_loader_ready", False)),
            "experience_package_manifest_ready": bool(readiness.get("readiness", {}).get("experience_package_manifest_ready", False)),
            "skill_manifest_loader_ready": bool(readiness.get("readiness", {}).get("skill_manifest_loader_ready", False)),
            "case_cause_fallback_ready": bool(readiness.get("readiness", {}).get("case_cause_fallback_ready", False)),
            "skill_context_dry_run_ready": bool(readiness.get("readiness", {}).get("skill_context_dry_run_ready", False)),
            "codex_fine_tune_training_disabled": bool(readiness.get("readiness", {}).get("codex_fine_tune_training_disabled", False)),
            "training_artifact_open_case_training_disabled": bool(readiness.get("readiness", {}).get("training_artifact_open_case_training_disabled", False)),
            "training_artifact_skill_auto_publish_disabled": bool(readiness.get("readiness", {}).get("training_artifact_skill_auto_publish_disabled", False)),
            "closed_case_training_run_ready": bool(readiness.get("readiness", {}).get("closed_case_training_run_ready", False)),
            "synthetic_closed_case_samples_ready": bool(readiness.get("readiness", {}).get("synthetic_closed_case_samples_ready", False)),
            "training_run_manifest_ready": bool(readiness.get("readiness", {}).get("training_run_manifest_ready", False)),
            "generated_experience_packages_ready": bool(readiness.get("readiness", {}).get("generated_experience_packages_ready", False)),
            "generated_skill_manifests_ready": bool(readiness.get("readiness", {}).get("generated_skill_manifests_ready", False)),
            "generated_evaluation_gate_test_cases_ready": bool(readiness.get("readiness", {}).get("generated_evaluation_gate_test_cases_ready", False)),
            "generated_loading_manifest_ready": bool(readiness.get("readiness", {}).get("generated_loading_manifest_ready", False)),
            "training_run_load_dry_run_ready": bool(readiness.get("readiness", {}).get("training_run_load_dry_run_ready", False)),
            "training_run_open_case_training_disabled": bool(readiness.get("readiness", {}).get("training_run_open_case_training_disabled", False)),
            "training_run_skill_auto_publish_disabled": bool(readiness.get("readiness", {}).get("training_run_skill_auto_publish_disabled", False)),
            "real_closed_case_training_intake_ready": bool(readiness.get("readiness", {}).get("real_closed_case_training_intake_ready", False)),
            "real_closed_case_redaction_pipeline_ready": bool(readiness.get("readiness", {}).get("real_closed_case_redaction_pipeline_ready", False)),
            "real_closed_case_classification_ready": bool(readiness.get("readiness", {}).get("real_closed_case_classification_ready", False)),
            "real_closed_case_training_sample_segmentation_ready": bool(readiness.get("readiness", {}).get("real_closed_case_training_sample_segmentation_ready", False)),
            "real_closed_case_open_case_training_disabled": bool(readiness.get("readiness", {}).get("real_closed_case_open_case_training_disabled", False)),
            "skill_final_drafts_aggregated": bool(readiness.get("readiness", {}).get("skill_final_drafts_aggregated", False)),
            "fact_outputs_aggregated": bool(readiness.get("readiness", {}).get("fact_outputs_aggregated", False)),
            "legal_drafts_aggregated": bool(readiness.get("readiness", {}).get("legal_drafts_aggregated", False)),
            "pilot_delivery_outputs_aggregated": bool(readiness.get("readiness", {}).get("pilot_delivery_outputs_aggregated", False)),
            "owner_only_download_ready": bool(readiness.get("readiness", {}).get("owner_only_download_ready", False)),
            "public_link_disabled": bool(readiness.get("readiness", {}).get("public_link_disabled", False)),
            "email_sending_disabled": bool(readiness.get("readiness", {}).get("email_sending_disabled", False)),
            "external_delivery_disabled": bool(readiness.get("readiness", {}).get("external_delivery_disabled", False)),
            "personal_production_pilot_gateway_registered": bool(readiness.get("readiness", {}).get("personal_production_pilot_gateway_registered", False)),
            "personal_case_workspace_gateway_registered": bool(readiness.get("readiness", {}).get("personal_case_workspace_gateway_registered", False)),
            "fact_preview_correction_workbench_gateway_registered": bool(readiness.get("readiness", {}).get("fact_preview_correction_workbench_gateway_registered", False)),
            "personal_production_pilot_dashboard_gateway_registered": bool(readiness.get("readiness", {}).get("personal_production_pilot_dashboard_gateway_registered", False)),
            "owner_download_gateway_registered": bool(readiness.get("readiness", {}).get("owner_download_gateway_registered", False)),
            "delivery_packet_gateway_registered": bool(readiness.get("readiness", {}).get("delivery_packet_gateway_registered", False)),
            "packet_item_gateway_registered": bool(readiness.get("readiness", {}).get("packet_item_gateway_registered", False)),
            "source_bundle_gateway_registered": bool(readiness.get("readiness", {}).get("source_bundle_gateway_registered", False)),
            "export_readiness_gateway_registered": bool(readiness.get("readiness", {}).get("export_readiness_gateway_registered", False)),
            "final_lock_gateway_registered": bool(readiness.get("readiness", {}).get("final_lock_gateway_registered", False)),
            "showcase_pack_gateway_registered": bool(readiness.get("readiness", {}).get("showcase_pack_gateway_registered", False)),
            "pilot_sample_gateway_registered": bool(readiness.get("readiness", {}).get("pilot_sample_gateway_registered", False)),
            "story_flow_gateway_registered": bool(readiness.get("readiness", {}).get("story_flow_gateway_registered", False)),
            "showcase_metrics_gateway_registered": bool(readiness.get("readiness", {}).get("showcase_metrics_gateway_registered", False)),
            "trust_panel_gateway_registered": bool(readiness.get("readiness", {}).get("trust_panel_gateway_registered", False)),
        },
        v7_23_readiness={
            "owner_output_center_ready": bool(readiness.get("readiness", {}).get("owner_output_center_ready", False)),
            "skill_final_drafts_aggregated": bool(readiness.get("readiness", {}).get("skill_final_drafts_aggregated", False)),
            "fact_outputs_aggregated": bool(readiness.get("readiness", {}).get("fact_outputs_aggregated", False)),
            "legal_drafts_aggregated": bool(readiness.get("readiness", {}).get("legal_drafts_aggregated", False)),
            "pilot_delivery_outputs_aggregated": bool(readiness.get("readiness", {}).get("pilot_delivery_outputs_aggregated", False)),
            "owner_only_download_ready": bool(readiness.get("readiness", {}).get("owner_only_download_ready", False)),
            "public_link_disabled": bool(readiness.get("readiness", {}).get("public_link_disabled", False)),
            "email_sending_disabled": bool(readiness.get("readiness", {}).get("email_sending_disabled", False)),
            "external_delivery_disabled": bool(readiness.get("readiness", {}).get("external_delivery_disabled", False)),
        },
        v7_25_readiness={
            "personal_trial_readiness_gateway_registered": bool(readiness.get("readiness", {}).get("personal_trial_readiness_gateway_registered", False)),
            "trial_readiness_ready": bool(readiness.get("readiness", {}).get("trial_readiness_ready", False)),
            "trial_checklist_ready": bool(readiness.get("readiness", {}).get("trial_checklist_ready", False)),
            "trial_issue_log_ready": bool(readiness.get("readiness", {}).get("trial_issue_log_ready", False)),
            "trial_quality_review_ready": bool(readiness.get("readiness", {}).get("trial_quality_review_ready", False)),
            "trial_safety_confirmation_ready": bool(readiness.get("readiness", {}).get("trial_safety_confirmation_ready", False)),
            "trial_optimization_backlog_ready": bool(readiness.get("readiness", {}).get("trial_optimization_backlog_ready", False)),
        },
        v7_26_readiness={
            "personal_provider_readiness_gateway_registered": bool(readiness.get("readiness", {}).get("personal_provider_readiness_gateway_registered", False)),
            "provider_readiness_ready": bool(readiness.get("readiness", {}).get("provider_readiness_ready", False)),
            "provider_registry_ready": bool(readiness.get("readiness", {}).get("provider_registry_ready", False)),
            "secret_boundary_ready": bool(readiness.get("readiness", {}).get("secret_boundary_ready", False)),
            "live_gate_ready": bool(readiness.get("readiness", {}).get("live_gate_ready", False)),
            "usage_cost_metadata_ready": bool(readiness.get("readiness", {}).get("usage_cost_metadata_ready", False)),
            "dry_run_health_ready": bool(readiness.get("readiness", {}).get("dry_run_health_ready", False)),
            "real_provider_calls_still_disabled": bool(readiness.get("readiness", {}).get("real_provider_calls_still_disabled", False)),
        },
        v7_27_readiness={
            "personal_material_live_connection_gateway_registered": bool(readiness.get("readiness", {}).get("personal_material_live_connection_gateway_registered", False)),
            "material_live_connection_ready": bool(readiness.get("readiness", {}).get("material_live_connection_ready", False)),
            "material_live_provider_registry_ready": bool(readiness.get("readiness", {}).get("material_live_provider_registry_ready", False)),
            "material_live_secret_boundary_ready": bool(readiness.get("readiness", {}).get("material_live_secret_boundary_ready", False)),
            "material_live_gate_ready": bool(readiness.get("readiness", {}).get("material_live_gate_ready", False)),
            "material_live_dry_run_health_ready": bool(readiness.get("readiness", {}).get("material_live_dry_run_health_ready", False)),
            "material_live_raw_content_blocked": bool(readiness.get("readiness", {}).get("material_live_raw_content_blocked", False)),
            "material_live_ai_prompt_injection_blocked": bool(readiness.get("readiness", {}).get("material_live_ai_prompt_injection_blocked", False)),
        },
        v7_28_readiness={
            "personal_live_connection_gateway_registered": bool(readiness.get("readiness", {}).get("personal_live_connection_gateway_registered", False)),
            "personal_live_connection_ready": bool(readiness.get("readiness", {}).get("personal_live_connection_ready", False)),
            "personal_live_connection_provider_registry_ready": bool(readiness.get("readiness", {}).get("personal_live_connection_provider_registry_ready", False)),
            "personal_live_connection_secret_boundary_ready": bool(readiness.get("readiness", {}).get("personal_live_connection_secret_boundary_ready", False)),
            "personal_live_connection_gate_ready": bool(readiness.get("readiness", {}).get("personal_live_connection_gate_ready", False)),
            "personal_live_connection_usage_cost_ready": bool(readiness.get("readiness", {}).get("personal_live_connection_usage_cost_ready", False)),
            "personal_live_connection_health_ready": bool(readiness.get("readiness", {}).get("personal_live_connection_health_ready", False)),
            "personal_live_connection_audit_ready": bool(readiness.get("readiness", {}).get("personal_live_connection_audit_ready", False)),
        },
        v7_29_readiness={
            "personal_legal_enterprise_gateway_registered": bool(readiness.get("readiness", {}).get("personal_legal_enterprise_gateway_registered", False)),
            "legal_enterprise_gateway_ready": bool(readiness.get("readiness", {}).get("legal_enterprise_gateway_ready", False)),
            "legal_provider_readiness_ready": bool(readiness.get("readiness", {}).get("legal_provider_readiness_ready", False)),
            "enterprise_provider_readiness_ready": bool(readiness.get("readiness", {}).get("enterprise_provider_readiness_ready", False)),
            "legal_source_trace_ready": bool(readiness.get("readiness", {}).get("legal_source_trace_ready", False)),
            "enterprise_verification_ready": bool(readiness.get("readiness", {}).get("enterprise_verification_ready", False)),
            "legal_enterprise_review_required": bool(readiness.get("readiness", {}).get("legal_enterprise_review_required", False)),
        },
        v7_30_readiness={
            "training_artifact_loader_gateway_registered": bool(readiness.get("readiness", {}).get("training_artifact_loader_gateway_registered", False)),
            "training_artifact_loader_ready": bool(readiness.get("readiness", {}).get("training_artifact_loader_ready", False)),
            "codex_training_scheme_ready": bool(readiness.get("readiness", {}).get("codex_training_scheme_ready", False)),
            "case_cause_taxonomy_ready": bool(readiness.get("readiness", {}).get("case_cause_taxonomy_ready", False)),
            "multi_level_case_cause_loader_ready": bool(readiness.get("readiness", {}).get("multi_level_case_cause_loader_ready", False)),
            "experience_package_manifest_ready": bool(readiness.get("readiness", {}).get("experience_package_manifest_ready", False)),
            "skill_manifest_loader_ready": bool(readiness.get("readiness", {}).get("skill_manifest_loader_ready", False)),
            "case_cause_fallback_ready": bool(readiness.get("readiness", {}).get("case_cause_fallback_ready", False)),
            "skill_context_dry_run_ready": bool(readiness.get("readiness", {}).get("skill_context_dry_run_ready", False)),
            "codex_fine_tune_training_disabled": bool(readiness.get("readiness", {}).get("codex_fine_tune_training_disabled", False)),
            "training_artifact_open_case_training_disabled": bool(readiness.get("readiness", {}).get("training_artifact_open_case_training_disabled", False)),
            "training_artifact_skill_auto_publish_disabled": bool(readiness.get("readiness", {}).get("training_artifact_skill_auto_publish_disabled", False)),
        },
        v7_31_readiness={
            "codex_training_run_gateway_registered": bool(readiness.get("readiness", {}).get("codex_training_run_gateway_registered", False)),
            "closed_case_training_run_ready": bool(readiness.get("readiness", {}).get("closed_case_training_run_ready", False)),
            "synthetic_closed_case_samples_ready": bool(readiness.get("readiness", {}).get("synthetic_closed_case_samples_ready", False)),
            "training_run_manifest_ready": bool(readiness.get("readiness", {}).get("training_run_manifest_ready", False)),
            "generated_experience_packages_ready": bool(readiness.get("readiness", {}).get("generated_experience_packages_ready", False)),
            "generated_skill_manifests_ready": bool(readiness.get("readiness", {}).get("generated_skill_manifests_ready", False)),
            "generated_evaluation_gate_test_cases_ready": bool(readiness.get("readiness", {}).get("generated_evaluation_gate_test_cases_ready", False)),
            "generated_loading_manifest_ready": bool(readiness.get("readiness", {}).get("generated_loading_manifest_ready", False)),
            "training_run_load_dry_run_ready": bool(readiness.get("readiness", {}).get("training_run_load_dry_run_ready", False)),
            "training_run_open_case_training_disabled": bool(readiness.get("readiness", {}).get("training_run_open_case_training_disabled", False)),
            "training_run_skill_auto_publish_disabled": bool(readiness.get("readiness", {}).get("training_run_skill_auto_publish_disabled", False)),
            "training_run_fine_tune_disabled": bool(readiness.get("readiness", {}).get("training_run_fine_tune_disabled", False)),
            "training_run_real_case_material_read_disabled": bool(readiness.get("readiness", {}).get("training_run_real_case_material_read_disabled", False)),
        },
        v7_31a_readiness={
            "real_closed_case_training_intake_gateway_registered": bool(readiness.get("readiness", {}).get("real_closed_case_training_intake_gateway_registered", False)),
            "real_closed_case_training_intake_ready": bool(readiness.get("readiness", {}).get("real_closed_case_training_intake_ready", False)),
            "real_closed_case_redaction_pipeline_ready": bool(readiness.get("readiness", {}).get("real_closed_case_redaction_pipeline_ready", False)),
            "real_closed_case_classification_ready": bool(readiness.get("readiness", {}).get("real_closed_case_classification_ready", False)),
            "real_closed_case_training_sample_segmentation_ready": bool(readiness.get("readiness", {}).get("real_closed_case_training_sample_segmentation_ready", False)),
            "real_closed_case_source_trace_ready": bool(readiness.get("readiness", {}).get("real_closed_case_source_trace_ready", False)),
            "real_closed_case_review_queue_ready": bool(readiness.get("readiness", {}).get("real_closed_case_review_queue_ready", False)),
            "real_closed_case_open_case_training_disabled": bool(readiness.get("readiness", {}).get("real_closed_case_open_case_training_disabled", False)),
            "real_closed_case_raw_content_blocked": bool(readiness.get("readiness", {}).get("real_closed_case_raw_content_blocked", False)),
            "real_closed_case_ready_for_codex_training": bool(readiness.get("readiness", {}).get("real_closed_case_ready_for_codex_training", False)),
        },
    ).model_dump()


def _runtime_registered(runtime_registry: dict, runtime_id: str) -> bool:
    for runtime in runtime_registry.get("runtimes", []):
        if isinstance(runtime, dict) and runtime.get("runtime_id") == runtime_id:
            return bool(runtime.get("enabled", False))
    return False


def _runtime_gateway_registered(runtime_registry: dict, runtime_id: str) -> bool:
    for runtime in runtime_registry.get("runtimes", []):
        if isinstance(runtime, dict) and runtime.get("runtime_id") == runtime_id:
            return bool(runtime.get("gateway_registered", False))
    return False
