from personal_production.schemas import PersonalProductionRuntimeItem, PersonalProductionRuntimeRegistry


RUNTIME_DEFINITIONS = [
    {
        "runtime_id": "ai_model_runtime",
        "label": "AI Model Runtime",
        "category": "ai",
        "target_route": "/personal-ai-gateway",
        "gateway_registered": True,
        "warnings": ["AI Gateway registered in v7.1. Live provider calls remain disabled."],
    },
    {
        "runtime_id": "material_parser_runtime",
        "label": "Material Parsing Runtime",
        "category": "material_parser",
        "target_route": "/personal-material-runtime",
        "gateway_registered": True,
        "warnings": ["MinerU and Docling placeholders registered in v7.2. Live parsing remains disabled."],
    },
    {
        "runtime_id": "ocr_runtime",
        "label": "OCR Runtime",
        "category": "ocr",
        "target_route": "/personal-material-runtime",
        "gateway_registered": True,
        "warnings": ["PaddleOCR-ready placeholder registered in v7.2. Live OCR remains disabled."],
    },
    {
        "runtime_id": "legal_search_runtime",
        "label": "Legal Search Runtime",
        "category": "legal_search",
        "target_route": "/personal-intelligence",
        "gateway_registered": True,
        "warnings": ["快查 365 LawSkills 占位已注册。v7.3 未调用真实法律检索服务。"],
    },
    {
        "runtime_id": "enterprise_intelligence_runtime",
        "label": "Enterprise Intelligence Runtime",
        "category": "enterprise_intelligence",
        "target_route": "/personal-intelligence",
        "gateway_registered": True,
        "warnings": ["天眼查 AI 占位已注册。v7.3 未调用真实企业信息服务。"],
    },
    {
        "runtime_id": "experience_package_studio_runtime",
        "label": "Experience Package Studio Runtime",
        "category": "skill_studio",
        "target_route": "/personal-skill-studio",
        "gateway_registered": True,
        "warnings": ["经验包工作室已注册。v7.4 不会自动发布 Skill。"],
    },
    {
        "runtime_id": "skill_candidate_studio_runtime",
        "label": "Skill Candidate Studio Runtime",
        "category": "skill_studio",
        "target_route": "/personal-skill-studio",
        "gateway_registered": True,
        "warnings": ["技能候选工作室已注册。v7.4 仅生成草案。"],
    },
    {
        "runtime_id": "skill_test_case_runtime",
        "label": "Skill Test Case Runtime",
        "category": "skill_studio",
        "target_route": "/personal-skill-studio",
        "gateway_registered": True,
        "warnings": ["技能测试用例工作室已注册。v7.4 仅生成 mock metadata。"],
    },
    {
        "runtime_id": "skill_evaluation_runtime",
        "label": "Skill Evaluation Runtime",
        "category": "skill_studio",
        "target_route": "/personal-skill-studio",
        "gateway_registered": True,
        "warnings": ["技能评估工作室已注册。v7.4 仅生成模拟评估。"],
    },
    {
        "runtime_id": "controlled_promotion_gate",
        "label": "Controlled Promotion Gate",
        "category": "skill_studio",
        "target_route": "/personal-skill-studio",
        "gateway_registered": True,
        "warnings": ["受控发布门禁已注册。v7.4 不会自动发布 Skill。"],
    },
    {
        "runtime_id": "case_production_runtime",
        "label": "Case Production Runtime",
        "category": "case_production",
        "target_route": "/personal-case-production",
        "gateway_registered": True,
        "warnings": ["真实案件生产工作流已注册。v7.5 不会自动对外交付。"],
    },
    {
        "runtime_id": "workflow_stage_orchestrator",
        "label": "Workflow Stage Orchestrator",
        "category": "case_production",
        "target_route": "/personal-case-production",
        "gateway_registered": True,
        "warnings": ["阶段编排器已注册。v7.5 仅生成流程 metadata。"],
    },
    {
        "runtime_id": "production_readiness_engine",
        "label": "Production Readiness Engine",
        "category": "case_production",
        "target_route": "/personal-case-production",
        "gateway_registered": True,
        "warnings": ["准备度引擎已注册。v7.5 不生成最终报告。"],
    },
    {
        "runtime_id": "lawyer_review_gate",
        "label": "Lawyer Review Gate",
        "category": "case_production",
        "target_route": "/personal-case-production",
        "gateway_registered": True,
        "warnings": ["律师复核门禁已注册。v7.5 不触发对外交付。"],
    },
    {
        "runtime_id": "delivery_packet_runtime",
        "label": "Personal Delivery Packet Runtime",
        "category": "delivery_packet",
        "target_route": "/personal-delivery-packet",
        "gateway_registered": True,
        "warnings": ["个人生产交付包已注册。v7.6 仅生成 metadata 草案，不生成真实 PDF/DOCX 或对外交付。"],
    },
    {
        "runtime_id": "packet_item_runtime",
        "label": "Packet Item Runtime",
        "category": "delivery_packet",
        "target_route": "/personal-delivery-packet",
        "gateway_registered": True,
        "warnings": ["交付项清单 Runtime 已注册。v7.6 仅生成交付项 metadata 草案。"],
    },
    {
        "runtime_id": "source_bundle_runtime",
        "label": "Source Bundle Runtime",
        "category": "delivery_packet",
        "target_route": "/personal-delivery-packet",
        "gateway_registered": True,
        "warnings": ["来源追踪包 Runtime 已注册。v7.6 不返回 raw content。"],
    },
    {
        "runtime_id": "export_readiness_engine",
        "label": "Delivery Export Readiness Engine",
        "category": "delivery_packet",
        "target_route": "/personal-delivery-packet",
        "gateway_registered": True,
        "warnings": ["受控导出准备度引擎已注册。export_ready 与 external_delivery_ready 默认保持 false。"],
    },
    {
        "runtime_id": "final_lock_engine",
        "label": "Delivery Final Lock Gate",
        "category": "delivery_packet",
        "target_route": "/personal-delivery-packet",
        "gateway_registered": True,
        "warnings": ["最终锁定门禁已注册。锁定仅更新 metadata，不触发真实导出、邮件或最终报告。"],
    },
    {
        "runtime_id": "showcase_pack_runtime",
        "label": "Showcase Pack Runtime",
        "category": "showcase_pack",
        "target_route": "/personal-showcase-pack",
        "gateway_registered": True,
        "warnings": ["展示包 Runtime 已注册。v7.7 仅组织 synthetic mock metadata。"],
    },
    {
        "runtime_id": "pilot_sample_runtime",
        "label": "Pilot Sample Runtime",
        "category": "showcase_pack",
        "target_route": "/personal-showcase-pack",
        "gateway_registered": True,
        "warnings": ["试点样本 Runtime 已注册。v7.7 不使用真实客户或真实案件信息。"],
    },
    {
        "runtime_id": "story_flow_runtime",
        "label": "Story Flow Runtime",
        "category": "showcase_pack",
        "target_route": "/personal-showcase-pack",
        "gateway_registered": True,
        "warnings": ["故事流程 Runtime 已注册。v7.7 仅串联 mock metadata。"],
    },
    {
        "runtime_id": "showcase_metrics_runtime",
        "label": "Showcase Metrics Runtime",
        "category": "showcase_pack",
        "target_route": "/personal-showcase-pack",
        "gateway_registered": True,
        "warnings": ["展示指标 Runtime 已注册。指标仅基于 synthetic mock metadata。"],
    },
    {
        "runtime_id": "trust_panel_runtime",
        "label": "Trust Panel Runtime",
        "category": "showcase_pack",
        "target_route": "/personal-showcase-pack",
        "gateway_registered": True,
        "warnings": ["安全与信任面板 Runtime 已注册。不会开启 live provider 或外部交付。"],
    },
    {"runtime_id": "skill_training_runtime", "label": "Skill Training Runtime", "category": "skill_training"},
    {"runtime_id": "delivery_runtime", "label": "Delivery Runtime", "category": "delivery"},
    {"runtime_id": "regression_runtime", "label": "Regression Runtime", "category": "regression", "warnings": []},
    {"runtime_id": "safety_runtime", "label": "Safety Runtime", "category": "safety", "warnings": []},
]


def build_runtime_registry() -> dict:
    runtimes = [
        PersonalProductionRuntimeItem(
            runtime_id=definition["runtime_id"],
            label=definition["label"],
            category=definition["category"],
            target_route=definition.get("target_route", "/personal-production"),
            gateway_registered=bool(definition.get("gateway_registered", False)),
            warnings=definition.get(
                "warnings",
                ["Runtime is registered for controlled foundation use; live mode remains disabled."],
            ),
        )
        for definition in RUNTIME_DEFINITIONS
    ]
    return PersonalProductionRuntimeRegistry(
        runtimes=runtimes,
        registered_runtime_count=len(runtimes),
        live_runtime_count=sum(1 for runtime in runtimes if runtime.live_enabled),
        controlled_runtime_count=sum(1 for runtime in runtimes if runtime.controlled_available),
    ).model_dump()
