from personal_production.schemas import PersonalProductionRuntimeItem, PersonalProductionRuntimeRegistry


RUNTIME_DEFINITIONS = [
    {
        "runtime_id": "ai_model_runtime",
        "label": "AI Model Runtime",
        "category": "ai",
        "target_route": "/personal-ai-gateway",
        "gateway_registered": True,
        "warnings": ["AI Gateway registered in v7.1. Live provider calls remain disabled."],
    },
    {
        "runtime_id": "ai_provider_live_gateway",
        "label": "AI Provider Live Gateway",
        "category": "ai",
        "target_route": "/personal-ai-gateway",
        "gateway_registered": True,
        "status": "planned_gated_disabled_by_default",
        "warnings": ["v7.12 live provider gateway is registered as dry-run-first. live provider disabled by default and requires explicit confirmation."],
    },
    {
        "runtime_id": "material_parser_runtime",
        "label": "Material Parsing Runtime",
        "category": "material_parser",
        "target_route": "/personal-material-runtime",
        "gateway_registered": True,
        "warnings": ["MinerU and Docling placeholders registered in v7.2. Live parsing remains disabled."],
    },
    {
        "runtime_id": "ocr_runtime",
        "label": "OCR Runtime",
        "category": "ocr",
        "target_route": "/personal-material-runtime",
        "gateway_registered": True,
        "warnings": ["PaddleOCR-ready placeholder registered in v7.2. Live OCR remains disabled."],
    },
    {
        "runtime_id": "ocr_document_provider_live_gateway",
        "label": "OCR / Document Provider Live Gateway",
        "category": "material_live_gateway",
        "target_route": "/personal-material-runtime",
        "gateway_registered": True,
        "status": "planned_gated_disabled_by_default",
        "warnings": [
            "v7.13 OCR / Document live gateway is dry-run-first.",
            "Live OCR and document parser providers are disabled by default.",
            "Raw OCR text and raw document content remain blocked and are not injected into AI prompts.",
        ],
    },
    {
        "runtime_id": "legal_search_runtime",
        "label": "Legal Search Runtime",
        "category": "legal_search",
        "target_route": "/personal-intelligence",
        "gateway_registered": True,
        "warnings": ["快查 365 LawSkills 占位已注册。v7.3 未调用真实法律检索服务。"],
    },
    {
        "runtime_id": "enterprise_intelligence_runtime",
        "label": "Enterprise Intelligence Runtime",
        "category": "enterprise_intelligence",
        "target_route": "/personal-intelligence",
        "gateway_registered": True,
        "warnings": ["天眼查 AI 占位已注册。v7.3 未调用真实企业信息服务。"],
    },
    {
        "runtime_id": "legal_enterprise_api_live_gateway",
        "label": "Legal / Enterprise API Live Gateway",
        "category": "intelligence_live_gateway",
        "target_route": "/personal-intelligence",
        "gateway_registered": True,
        "status": "planned_gated_disabled_by_default",
        "warnings": [
            "v7.14 Legal / Enterprise API live gateway is dry-run-first.",
            "Live legal and enterprise providers are disabled by default.",
            "Citation candidates are metadata only and are not final citations.",
        ],
    },
    {
        "runtime_id": "experience_package_studio_runtime",
        "label": "Experience Package Studio Runtime",
        "category": "skill_studio",
        "target_route": "/personal-skill-studio",
        "gateway_registered": True,
        "warnings": ["经验包工作室已注册。v7.4 不会自动发布 Skill。"],
    },
    {
        "runtime_id": "skill_candidate_studio_runtime",
        "label": "Skill Candidate Studio Runtime",
        "category": "skill_studio",
        "target_route": "/personal-skill-studio",
        "gateway_registered": True,
        "warnings": ["技能候选工作室已注册。v7.4 仅生成草案。"],
    },
    {
        "runtime_id": "skill_test_case_runtime",
        "label": "Skill Test Case Runtime",
        "category": "skill_studio",
        "target_route": "/personal-skill-studio",
        "gateway_registered": True,
        "warnings": ["技能测试用例工作室已注册。v7.4 仅生成 mock metadata。"],
    },
    {
        "runtime_id": "skill_evaluation_runtime",
        "label": "Skill Evaluation Runtime",
        "category": "skill_studio",
        "target_route": "/personal-skill-studio",
        "gateway_registered": True,
        "warnings": ["技能评估工作室已注册。v7.4 仅生成模拟评估。"],
    },
    {
        "runtime_id": "controlled_promotion_gate",
        "label": "Controlled Promotion Gate",
        "category": "skill_studio",
        "target_route": "/personal-skill-studio",
        "gateway_registered": True,
        "warnings": ["受控发布门禁已注册。v7.4 不会自动发布 Skill。"],
    },
    {
        "runtime_id": "skill_final_draft_workbench_runtime",
        "label": "Skill Final Draft & Optimization Workbench Runtime",
        "category": "skill_studio",
        "target_route": "/personal-skill-studio/final-drafts",
        "gateway_registered": True,
        "status": "skill_final_draft_metadata_ready",
        "warnings": [
            "v7.22 两个 Skill 最终稿与优化工作台已注册。",
            "基于既有 Skill 和配套材料 metadata 生成 final draft metadata。",
            "仅用户本人下载，不自动发布 Skill，不自动训练未结案件。",
        ],
    },
    {
        "runtime_id": "case_production_runtime",
        "label": "Case Production Runtime",
        "category": "case_production",
        "target_route": "/personal-case-production",
        "gateway_registered": True,
        "warnings": ["真实案件生产工作流已注册。v7.5 不会自动对外交付。"],
    },
    {
        "runtime_id": "controlled_case_analysis_runtime",
        "label": "Controlled Case Analysis Runtime",
        "category": "case_analysis",
        "target_route": "/personal-case-analysis",
        "gateway_registered": True,
        "status": "planned_gated_draft_only",
        "warnings": [
            "v7.16 未结案件实战分析 Runtime 已注册。",
            "仅调用已有 Skill metadata，输出 fact / legal analysis draft。",
            "不产生训练数据，不自动更新或发布 Skill。",
        ],
    },
    {
        "runtime_id": "case_fact_analysis_stage",
        "label": "Case Fact Analysis Stage",
        "category": "case_analysis",
        "target_route": "/personal-case-analysis",
        "gateway_registered": True,
        "status": "draft_only_reference",
        "warnings": ["案件事实分析阶段仅生成事实摘要、证据映射、时间线和争议事实 draft metadata。"],
    },
    {
        "runtime_id": "case_legal_analysis_stage",
        "label": "Case Legal Analysis Stage",
        "category": "case_analysis",
        "target_route": "/personal-case-analysis",
        "gateway_registered": True,
        "status": "draft_only_reference",
        "warnings": ["案件法律分析阶段仅生成法律关系、争议焦点、请求权基础和抗辩路径 draft metadata。"],
    },
    {
        "runtime_id": "legal_analysis_draft_workbench_runtime",
        "label": "Legal Analysis Draft Workbench Runtime",
        "category": "case_analysis",
        "target_route": "/personal-case-analysis/legal-drafts",
        "gateway_registered": True,
        "status": "legal_analysis_draft_metadata_ready",
        "warnings": [
            "v7.21 法律分析草稿工作台已注册。",
            "基于 v7.20 事实输入 metadata 生成法律分析草稿。",
            "不生成最终法律意见、最终报告、真实文件、邮件或外部交付。",
        ],
    },
    {
        "runtime_id": "personal_production_pilot_runtime",
        "label": "Personal Production Pilot Runtime",
        "category": "production_pilot",
        "target_route": "/personal-production-pilot",
        "gateway_registered": True,
        "status": "ready_gated_owner_download_only",
        "warnings": [
            "v7.17 个人生产实战 Pilot 已注册。",
            "串联 AI / OCR / Legal / Enterprise / Skill / Case Analysis / Delivery Packet。",
            "仅允许用户本人下载 metadata；不自动邮件、公开链接或对外交付。",
        ],
    },
    {
        "runtime_id": "personal_case_workspace_runtime",
        "label": "Personal Case & Material Workspace Runtime",
        "category": "case_workspace",
        "target_route": "/personal-case-workspace",
        "gateway_registered": True,
        "status": "owner_only_metadata_ready",
        "warnings": [
            "v7.18 个人案件与材料工作台已注册。",
            "材料列表、OCR 状态、事实输入纠正和 owner raw view 均为 metadata-only / owner-only。",
            "不读取真实材料，不返回 raw content，不写训练集。",
        ],
    },
    {
        "runtime_id": "fact_preview_correction_workbench_runtime",
        "label": "Fact Preview & Correction Workbench Runtime",
        "category": "case_workspace",
        "target_route": "/personal-case-workspace",
        "gateway_registered": True,
        "status": "fact_preview_correction_metadata_ready",
        "warnings": [
            "v7.20 事实预览与输入纠正工作台已注册。",
            "事实预览、纠正、版本、质量评分、门控和法律分析输入 ready 均为 metadata-only。",
            "不会自动触发法律分析、训练 Skill、发布 Skill、生成最终事实认定或对外交付。",
        ],
    },
    {
        "runtime_id": "personal_production_pilot_dashboard_runtime",
        "label": "Personal Production Pilot Dashboard Runtime",
        "category": "production_pilot",
        "target_route": "/personal-production-pilot",
        "gateway_registered": True,
        "status": "dashboard_metadata_ready",
        "warnings": [
            "v7.19 Pilot Dashboard 增强已注册。",
            "质量评分、门控和优化建议仅为参考 metadata，不构成最终法律意见或正式报告。",
        ],
    },
    {
        "runtime_id": "owner_download_runtime",
        "label": "Owner Download Runtime",
        "category": "production_pilot",
        "target_route": "/personal-production-pilot",
        "gateway_registered": True,
        "status": "owner_only_download_metadata",
        "warnings": ["Owner Download 仅生成用户本人下载 metadata，不创建公开链接、不发送邮件、不外部交付。"],
    },
    {
        "runtime_id": "personal_owner_output_center_runtime",
        "label": "Owner-only Output Center Runtime",
        "category": "owner_output_center",
        "target_route": "/personal-owner-output-center",
        "gateway_registered": True,
        "status": "owner_output_center_metadata_ready",
        "warnings": [
            "v7.23 用户本人产出下载中心已注册。",
            "聚合 Skill 最终稿、事实产出、法律分析草稿、Pilot / Delivery 草稿。",
            "仅用户本人查看和下载，不创建公开链接、不发送邮件、不自动对外交付。",
        ],
    },
    {
        "runtime_id": "workflow_stage_orchestrator",
        "label": "Workflow Stage Orchestrator",
        "category": "case_production",
        "target_route": "/personal-case-production",
        "gateway_registered": True,
        "warnings": ["阶段编排器已注册。v7.5 仅生成流程 metadata。"],
    },
    {
        "runtime_id": "production_readiness_engine",
        "label": "Production Readiness Engine",
        "category": "case_production",
        "target_route": "/personal-case-production",
        "gateway_registered": True,
        "warnings": ["准备度引擎已注册。v7.5 不生成最终报告。"],
    },
    {
        "runtime_id": "lawyer_review_gate",
        "label": "Lawyer Review Gate",
        "category": "case_production",
        "target_route": "/personal-case-production",
        "gateway_registered": True,
        "warnings": ["律师复核门禁已注册。v7.5 不触发对外交付。"],
    },
    {
        "runtime_id": "delivery_packet_runtime",
        "label": "Personal Delivery Packet Runtime",
        "category": "delivery_packet",
        "target_route": "/personal-delivery-packet",
        "gateway_registered": True,
        "warnings": ["个人生产交付包已注册。v7.6 仅生成 metadata 草案，不生成真实 PDF/DOCX 或对外交付。"],
    },
    {
        "runtime_id": "packet_item_runtime",
        "label": "Packet Item Runtime",
        "category": "delivery_packet",
        "target_route": "/personal-delivery-packet",
        "gateway_registered": True,
        "warnings": ["交付项清单 Runtime 已注册。v7.6 仅生成交付项 metadata 草案。"],
    },
    {
        "runtime_id": "source_bundle_runtime",
        "label": "Source Bundle Runtime",
        "category": "delivery_packet",
        "target_route": "/personal-delivery-packet",
        "gateway_registered": True,
        "warnings": ["来源追踪包 Runtime 已注册。v7.6 不返回 raw content。"],
    },
    {
        "runtime_id": "export_readiness_engine",
        "label": "Delivery Export Readiness Engine",
        "category": "delivery_packet",
        "target_route": "/personal-delivery-packet",
        "gateway_registered": True,
        "warnings": ["受控导出准备度引擎已注册。export_ready 与 external_delivery_ready 默认保持 false。"],
    },
    {
        "runtime_id": "final_lock_engine",
        "label": "Delivery Final Lock Gate",
        "category": "delivery_packet",
        "target_route": "/personal-delivery-packet",
        "gateway_registered": True,
        "warnings": ["最终锁定门禁已注册。锁定仅更新 metadata，不触发真实导出、邮件或最终报告。"],
    },
    {
        "runtime_id": "showcase_pack_runtime",
        "label": "Showcase Pack Runtime",
        "category": "showcase_pack",
        "target_route": "/personal-showcase-pack",
        "gateway_registered": True,
        "warnings": ["展示包 Runtime 已注册。v7.7 仅组织 synthetic mock metadata。"],
    },
    {
        "runtime_id": "pilot_sample_runtime",
        "label": "Pilot Sample Runtime",
        "category": "showcase_pack",
        "target_route": "/personal-showcase-pack",
        "gateway_registered": True,
        "warnings": ["试点样本 Runtime 已注册。v7.7 不使用真实客户或真实案件信息。"],
    },
    {
        "runtime_id": "story_flow_runtime",
        "label": "Story Flow Runtime",
        "category": "showcase_pack",
        "target_route": "/personal-showcase-pack",
        "gateway_registered": True,
        "warnings": ["故事流程 Runtime 已注册。v7.7 仅串联 mock metadata。"],
    },
    {
        "runtime_id": "showcase_metrics_runtime",
        "label": "Showcase Metrics Runtime",
        "category": "showcase_pack",
        "target_route": "/personal-showcase-pack",
        "gateway_registered": True,
        "warnings": ["展示指标 Runtime 已注册。指标仅基于 synthetic mock metadata。"],
    },
    {
        "runtime_id": "trust_panel_runtime",
        "label": "Trust Panel Runtime",
        "category": "showcase_pack",
        "target_route": "/personal-showcase-pack",
        "gateway_registered": True,
        "warnings": ["安全与信任面板 Runtime 已注册。不会开启 live provider 或外部交付。"],
    },
    {"runtime_id": "skill_training_runtime", "label": "Skill Training Runtime", "category": "skill_training"},
    {"runtime_id": "delivery_runtime", "label": "Delivery Runtime", "category": "delivery"},
    {"runtime_id": "regression_runtime", "label": "Regression Runtime", "category": "regression", "warnings": []},
    {"runtime_id": "safety_runtime", "label": "Safety Runtime", "category": "safety", "warnings": []},
]


def build_runtime_registry() -> dict:
    runtimes = [
        PersonalProductionRuntimeItem(
            runtime_id=definition["runtime_id"],
            label=definition["label"],
            category=definition["category"],
            target_route=definition.get("target_route", "/personal-production"),
            gateway_registered=bool(definition.get("gateway_registered", False)),
            status=definition.get("status", "registered_not_live"),
            warnings=definition.get(
                "warnings",
                ["Runtime is registered for controlled foundation use; live mode remains disabled."],
            ),
        )
        for definition in RUNTIME_DEFINITIONS
    ]
    return PersonalProductionRuntimeRegistry(
        runtimes=runtimes,
        registered_runtime_count=len(runtimes),
        live_runtime_count=sum(1 for runtime in runtimes if runtime.live_enabled),
        controlled_runtime_count=sum(1 for runtime in runtimes if runtime.controlled_available),
    ).model_dump()
