from personal_skill_studio.training_artifacts.schemas import ClosedCaseTrainingSample


SAMPLES = [
    ClosedCaseTrainingSample(
        sample_id="synthetic_closed_case_sales_contract_001",
        case_domain="civil",
        case_cause_level_1="contract_dispute",
        case_cause_level_2="sales_contract_dispute",
        case_cause_name="买卖合同纠纷",
        case_cause_code="civil.contract.sales",
        case_cause_path=["civil", "contract_dispute", "sales_contract_dispute"],
        parent_case_cause_id="civil_contract_dispute",
        case_cause_scope="civil.contract_dispute.sales_contract_dispute",
        applicable_fact_patterns=["订单形成", "交付验收", "对账欠款", "质量异议"],
        applicable_legal_relationships=["买卖合同关系", "付款请求权", "质量抗辩"],
        applicable_evidence_types=["contract", "invoice", "delivery_record", "reconciliation_record"],
        applicable_claim_basis=["支付货款", "违约责任"],
        applicable_defense_patterns=["质量抗辩", "履行抗辩"],
        fallback_case_cause_path=["civil", "contract_dispute"],
    ),
    ClosedCaseTrainingSample(
        sample_id="synthetic_closed_case_loan_contract_001",
        case_domain="civil",
        case_cause_level_1="contract_dispute",
        case_cause_level_2="loan_contract_dispute",
        case_cause_name="民间借贷纠纷",
        case_cause_code="civil.contract.loan",
        case_cause_path=["civil", "contract_dispute", "loan_contract_dispute"],
        parent_case_cause_id="civil_contract_dispute",
        case_cause_scope="civil.contract_dispute.loan_contract_dispute",
        applicable_fact_patterns=["借款交付", "利息约定", "还款节点", "催收记录"],
        applicable_legal_relationships=["借款合同关系", "本金返还", "利息边界"],
        applicable_evidence_types=["loan_contract", "transfer_record", "repayment_record", "guarantee_record"],
        applicable_claim_basis=["返还借款", "支付利息"],
        applicable_defense_patterns=["已还款抗辩", "利息过高抗辩"],
        fallback_case_cause_path=["civil", "contract_dispute"],
    ),
    ClosedCaseTrainingSample(
        sample_id="synthetic_closed_case_traffic_accident_001",
        case_domain="civil",
        case_cause_level_1="tort_dispute",
        case_cause_level_2="traffic_accident_dispute",
        case_cause_name="机动车交通事故责任纠纷",
        case_cause_code="civil.tort.traffic",
        case_cause_path=["civil", "tort_dispute", "traffic_accident_dispute"],
        parent_case_cause_id="civil_tort_dispute",
        case_cause_scope="civil.tort_dispute.traffic_accident_dispute",
        applicable_fact_patterns=["事故经过", "责任认定", "损害项目", "保险关系"],
        applicable_legal_relationships=["侵权责任", "保险责任", "损害赔偿"],
        applicable_evidence_types=["traffic_accident_certificate", "medical_record", "insurance_policy"],
        applicable_claim_basis=["人身损害赔偿", "财产损害赔偿"],
        applicable_defense_patterns=["责任比例抗辩", "损失范围抗辩"],
        fallback_case_cause_path=["civil", "tort_dispute"],
    ),
    ClosedCaseTrainingSample(
        sample_id="synthetic_closed_case_divorce_001",
        case_domain="civil",
        case_cause_level_1="marriage_inheritance",
        case_cause_level_2="divorce_dispute",
        case_cause_name="离婚纠纷",
        case_cause_code="civil.marriage.divorce",
        case_cause_path=["civil", "marriage_inheritance", "divorce_dispute"],
        parent_case_cause_id="civil_marriage_inheritance",
        case_cause_scope="civil.marriage_inheritance.divorce_dispute",
        applicable_fact_patterns=["婚姻关系", "子女抚养", "财产范围", "过错事实"],
        applicable_legal_relationships=["婚姻关系解除", "共同财产分割", "子女抚养"],
        applicable_evidence_types=["identity_record", "property_record", "child_care_record"],
        applicable_claim_basis=["离婚请求", "财产分割请求"],
        applicable_defense_patterns=["感情未破裂抗辩", "财产范围抗辩"],
        fallback_case_cause_path=["civil", "marriage_inheritance"],
    ),
    ClosedCaseTrainingSample(
        sample_id="synthetic_closed_case_labor_contract_001",
        case_domain="civil",
        case_cause_level_1="labor_dispute",
        case_cause_level_2="labor_contract_dispute",
        case_cause_name="劳动合同纠纷",
        case_cause_code="civil.labor.contract",
        case_cause_path=["civil", "labor_dispute", "labor_contract_dispute"],
        parent_case_cause_id="civil_labor_dispute",
        case_cause_scope="civil.labor_dispute.labor_contract_dispute",
        applicable_fact_patterns=["劳动关系", "工资支付", "解除通知", "社保缴纳"],
        applicable_legal_relationships=["劳动合同关系", "工资请求", "经济补偿"],
        applicable_evidence_types=["labor_contract", "salary_record", "termination_notice"],
        applicable_claim_basis=["工资支付", "经济补偿"],
        applicable_defense_patterns=["已支付抗辩", "合法解除抗辩"],
        fallback_case_cause_path=["civil"],
    ),
]


def list_training_samples() -> list[ClosedCaseTrainingSample]:
    return list(SAMPLES)

