from personal_owner_output_center.schemas import OwnerOutputRecord


TIMESTAMP = "2026-06-06T10:23:00Z"


def _output(
    output_id: str,
    output_type: str,
    output_title: str,
    source_runtime: str,
    source_module: str,
    source_id: str,
    quality_score: int,
    gate_status: str,
    source_trace_count: int,
    optimization_suggestions: list[str],
    dimension_scores: dict[str, int],
    case_id: str | None = None,
    skill_id: str | None = None,
) -> OwnerOutputRecord:
    return OwnerOutputRecord(
        output_id=output_id,
        output_type=output_type,
        output_title=output_title,
        source_runtime=source_runtime,
        source_module=source_module,
        source_id=source_id,
        case_id=case_id,
        skill_id=skill_id,
        quality_score=quality_score,
        gate_status=gate_status,
        source_trace_count=source_trace_count,
        optimization_suggestions=optimization_suggestions,
        dimension_scores=dimension_scores,
        created_at=TIMESTAMP,
        updated_at=TIMESTAMP,
        warnings=[
            "This output is owner-only draft metadata.",
            "No public link, email, final opinion, formal report, or external delivery is created.",
        ],
    )


OUTPUTS: list[OwnerOutputRecord] = [
    _output(
        output_id="owner_output_skill_fact_final_draft",
        output_type="skill_final_draft",
        output_title="案件事实提炼 Skill 最终稿 metadata",
        source_runtime="skill_final_draft_workbench_runtime",
        source_module="personal_skill_studio",
        source_id="case_fact_extraction_skill",
        skill_id="case_fact_extraction_skill",
        quality_score=76,
        gate_status="reference_ready",
        source_trace_count=4,
        optimization_suggestions=["补齐事实模式样本 metadata。", "继续保持 source trace 与律师复核边界。"],
        dimension_scores={"lineage": 80, "source_trace": 78, "review_readiness": 74},
    ),
    _output(
        output_id="owner_output_skill_legal_final_draft",
        output_type="skill_final_draft",
        output_title="案件法律分析 Skill 最终稿 metadata",
        source_runtime="skill_final_draft_workbench_runtime",
        source_module="personal_skill_studio",
        source_id="case_legal_analysis_skill",
        skill_id="case_legal_analysis_skill",
        quality_score=78,
        gate_status="reference_ready",
        source_trace_count=4,
        optimization_suggestions=["补齐请求权基础样本 metadata。", "将风险提示与法律结论继续分离。"],
        dimension_scores={"lineage": 82, "legal_pattern": 78, "review_readiness": 76},
    ),
    _output(
        output_id="owner_output_fact_preview_draft",
        output_type="fact_preview_draft",
        output_title="事实预览草稿 metadata",
        source_runtime="fact_preview_correction_workbench_runtime",
        source_module="personal_case_workspace",
        source_id="fact_preview_mock_001",
        case_id="case_workspace_mock_001",
        quality_score=82,
        gate_status="quality_reference_only",
        source_trace_count=6,
        optimization_suggestions=["补齐缺失付款节点 metadata。", "低置信度事实继续进入用户本人纠正。"],
        dimension_scores={"fact_summary": 84, "timeline": 78, "source_trace": 86},
    ),
    _output(
        output_id="owner_output_fact_correction_version",
        output_type="fact_correction_version",
        output_title="事实纠正版本 metadata",
        source_runtime="fact_preview_correction_workbench_runtime",
        source_module="personal_case_workspace",
        source_id="fact_version_mock_001",
        case_id="case_workspace_mock_001",
        quality_score=80,
        gate_status="owner_review_required",
        source_trace_count=5,
        optimization_suggestions=["确认纠正原因 metadata。", "保留版本差异供律师复核。"],
        dimension_scores={"correction_clarity": 80, "audit": 82, "source_trace": 78},
    ),
    _output(
        output_id="owner_output_fact_source_trace_summary",
        output_type="fact_source_trace_summary",
        output_title="事实来源追踪摘要 metadata",
        source_runtime="fact_preview_correction_workbench_runtime",
        source_module="personal_case_workspace",
        source_id="fact_source_trace_summary_mock_001",
        case_id="case_workspace_mock_001",
        quality_score=84,
        gate_status="reference_ready",
        source_trace_count=8,
        optimization_suggestions=["将未确认来源继续保留为复核项。"],
        dimension_scores={"trace_coverage": 86, "audit": 84, "raw_boundary": 88},
    ),
    _output(
        output_id="owner_output_fact_quality_gate_report",
        output_type="fact_quality_gate_report",
        output_title="事实质量与门控报告 metadata",
        source_runtime="fact_preview_correction_workbench_runtime",
        source_module="personal_case_workspace",
        source_id="fact_gate_mock_001",
        case_id="case_workspace_mock_001",
        quality_score=81,
        gate_status="reference_only_not_blocking",
        source_trace_count=3,
        optimization_suggestions=["质量门控仅用于优化建议，不阻断用户本人下载。"],
        dimension_scores={"quality": 81, "gate": 79, "optimization": 83},
    ),
    _output(
        output_id="owner_output_legal_analysis_draft",
        output_type="legal_analysis_draft",
        output_title="法律分析草稿 metadata",
        source_runtime="legal_analysis_draft_workbench_runtime",
        source_module="personal_case_analysis",
        source_id="legal_analysis_draft_mock_001",
        case_id="open_case_mock_001",
        quality_score=81,
        gate_status="lawyer_review_required",
        source_trace_count=5,
        optimization_suggestions=["补充法律检索候选来源。", "继续避免最终意见措辞。"],
        dimension_scores={"summary": 82, "claim_basis": 78, "risk_note": 84},
    ),
    _output(
        output_id="owner_output_issue_spotting_draft",
        output_type="issue_spotting_draft",
        output_title="争议焦点识别草稿 metadata",
        source_runtime="legal_analysis_draft_workbench_runtime",
        source_module="personal_case_analysis",
        source_id="issue_spotting_mock_001",
        case_id="open_case_mock_001",
        quality_score=79,
        gate_status="reference_only_not_blocking",
        source_trace_count=4,
        optimization_suggestions=["区分事实争议与法律争议。"],
        dimension_scores={"issue_coverage": 80, "clarity": 78, "review": 79},
    ),
    _output(
        output_id="owner_output_claim_basis_draft",
        output_type="claim_basis_draft",
        output_title="请求权基础草稿 metadata",
        source_runtime="legal_analysis_draft_workbench_runtime",
        source_module="personal_case_analysis",
        source_id="claim_basis_mock_001",
        case_id="open_case_mock_001",
        quality_score=77,
        gate_status="source_trace_review_required",
        source_trace_count=3,
        optimization_suggestions=["补齐法律依据候选 source trace。"],
        dimension_scores={"claim_basis": 77, "source_trace": 75, "review": 80},
    ),
    _output(
        output_id="owner_output_defense_path_draft",
        output_type="defense_path_draft",
        output_title="抗辩路径草稿 metadata",
        source_runtime="legal_analysis_draft_workbench_runtime",
        source_module="personal_case_analysis",
        source_id="defense_path_mock_001",
        case_id="open_case_mock_001",
        quality_score=76,
        gate_status="reference_only_not_blocking",
        source_trace_count=3,
        optimization_suggestions=["将抗辩路径与风险提示分开展示。"],
        dimension_scores={"defense_path": 76, "evidence_gap": 74, "review": 80},
    ),
    _output(
        output_id="owner_output_risk_warning_draft",
        output_type="risk_warning_draft",
        output_title="风险提示草稿 metadata",
        source_runtime="legal_analysis_draft_workbench_runtime",
        source_module="personal_case_analysis",
        source_id="risk_warning_mock_001",
        case_id="open_case_mock_001",
        quality_score=83,
        gate_status="lawyer_review_required",
        source_trace_count=4,
        optimization_suggestions=["风险提示不得描述为结果保证。"],
        dimension_scores={"risk_coverage": 84, "language_safety": 86, "review": 80},
    ),
    _output(
        output_id="owner_output_next_action_checklist_draft",
        output_type="next_action_checklist_draft",
        output_title="下一步行动清单草稿 metadata",
        source_runtime="legal_analysis_draft_workbench_runtime",
        source_module="personal_case_analysis",
        source_id="next_action_checklist_mock_001",
        case_id="open_case_mock_001",
        quality_score=85,
        gate_status="reference_ready",
        source_trace_count=2,
        optimization_suggestions=["将补充材料、律师复核和 source trace 分为独立检查项。"],
        dimension_scores={"actionability": 86, "review": 84, "trace": 82},
    ),
    _output(
        output_id="owner_output_pilot_summary",
        output_type="production_pilot_summary",
        output_title="个人生产 Pilot 摘要 metadata",
        source_runtime="personal_production_pilot_runtime",
        source_module="personal_production_pilot",
        source_id="pilot_summary_mock_001",
        case_id="open_case_pilot_mock_001",
        quality_score=82,
        gate_status="reference_ready",
        source_trace_count=6,
        optimization_suggestions=["保持 provider gated 与 owner-only download 状态。"],
        dimension_scores={"workflow": 83, "safety": 88, "review": 78},
    ),
    _output(
        output_id="owner_output_review_summary",
        output_type="review_summary",
        output_title="复核摘要 metadata",
        source_runtime="personal_production_pilot_runtime",
        source_module="personal_production_pilot",
        source_id="review_summary_mock_001",
        case_id="open_case_pilot_mock_001",
        quality_score=80,
        gate_status="lawyer_review_required",
        source_trace_count=4,
        optimization_suggestions=["将 pending review 与 revision required 分开展示。"],
        dimension_scores={"review_queue": 80, "audit": 82, "safety": 84},
    ),
    _output(
        output_id="owner_output_pilot_source_trace_summary",
        output_type="pilot_source_trace_summary",
        output_title="Pilot 来源追踪摘要 metadata",
        source_runtime="personal_production_pilot_dashboard_runtime",
        source_module="personal_production_pilot",
        source_id="pilot_source_trace_summary_mock_001",
        case_id="open_case_pilot_mock_001",
        quality_score=84,
        gate_status="reference_ready",
        source_trace_count=14,
        optimization_suggestions=["继续将未确认来源保留在复核队列。"],
        dimension_scores={"coverage": 84, "confirmed": 82, "audit": 86},
    ),
    _output(
        output_id="owner_output_delivery_packet_draft",
        output_type="delivery_packet_draft",
        output_title="交付包草稿 metadata",
        source_runtime="personal_delivery_packet_runtime",
        source_module="personal_delivery_packet",
        source_id="delivery_packet_mock_001",
        case_id="open_case_pilot_mock_001",
        quality_score=78,
        gate_status="draft_only",
        source_trace_count=5,
        optimization_suggestions=["仅保留草稿与 owner-only 下载 metadata，不生成正式文件。"],
        dimension_scores={"packet": 78, "boundary": 88, "review": 76},
    ),
    _output(
        output_id="owner_output_export_boundary_summary",
        output_type="export_boundary_summary",
        output_title="导出边界摘要 metadata",
        source_runtime="personal_production_pilot_runtime",
        source_module="personal_production_pilot",
        source_id="export_boundary_mock_001",
        case_id="open_case_pilot_mock_001",
        quality_score=90,
        gate_status="safety_boundary_ready",
        source_trace_count=3,
        optimization_suggestions=["继续禁止公开链接、邮件、第三方上传和外部交付。"],
        dimension_scores={"public_link": 100, "email": 100, "external_delivery": 100},
    ),
]


def list_registry_outputs() -> list[OwnerOutputRecord]:
    return OUTPUTS


def get_registry_output(output_id: str) -> OwnerOutputRecord | None:
    for output in OUTPUTS:
        if output.output_id == output_id:
            return output
    return None
